name: Build devcontainer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: /workspace/igou-devenv/tests/test-tools.sh
